[package]
name = "hardwmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.17.1"
nvml-wrapper = "0.9.0"
psutil = "3.2.2"
round = "0.1.2"
sysinfo = "0.28.4"
